/* eslint-disable */
// @ts-nocheck
/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

export {}

declare module "vue-router" {
  type RouteNamedMap = import("vue-router/auto-routes").RouteNamedMap;

  export interface TypesConfig {
    RouteNamedMap: RouteNamedMap;
  }
}

declare module "vue-router/auto-routes" {
  import type { RouteParamsRawGeneric, RouteParamsGeneric, RouteMeta, RouteRecordInfo, ParamValue, ParamValueZeroOrOne } from "vue-router";

  /**
   * route named map
  */
  export interface RouteNamedMap {
    "Root": RouteRecordInfo<"Root", "/", Record<never, never>, Record<never, never>>;
    "NotFound": RouteRecordInfo<"NotFound", "/:pathMatch(.*)*", Record<never, never>, Record<never, never>>
  }
}
